### ISSUE TITLE
phpMyAdmin49 4.9.3 ready for release

### ISSUE THREAD

**Issue by petecassetta** [iusrepo/phpMyAdmin49#2]
Just wanted to let you know I've tested phpMyAdmin49 4.9.3-1 on both CentOS 6 & 7. Everything looks good to me, so I feel this version is ready to be pushed from testing --> release.

**Comment by carlwgeorge** [comment]
Awesome, thanks for testing @petecassetta.  I'll push this update to the main repos on Monday.

**Comment by carlwgeorge** [comment]
I've pushed the update to the main repos.
